[build]
  publish = "public"
  command = "npm install --legacy-peer-deps && npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
