backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Uvodni stranka"
        name: "index"
        fields:
          - {label: 'Upozorneni', name: 'disclaimer', widget: 'markdown'}
          - {label: Uvodni text, name: uvodni_text, widget: object, fields: [{label: Prvni radek, name: firstRow, widget: string, required: false}, {label: Druhy radek, name: secondRow, widget: string, required: false}, {label: Treti radek, name: thirdRow, widget: string, required: false}, {label: Barevne slovo, name: coloredText, widget: string, required: false}]}
          - {label: Uvodni foto, name: uvodni_foto, widget: object, fields: [{label: Obrazek1, name: obrazek1, widget: image}, {label: Obrazek2, name: obrazek2, widget: image}, {label: Obrazek3, name: obrazek3, widget: image}]}
          - {label: Sekce, name: section, widget: object, fields: [{label: Nadpis, name: section_heading, widget: string}, {label: Text, name: section_text, widget: text}, {label: Obrazek, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}